### ISSUE TITLE
problem to downloading the package via npm

### ISSUE THREAD

**Issue by bloudman** [joeferner/node-serialport2#24]
Registry url: https://registry.npmjs.org/
Current Time: 20/09/2015 21:16:10
Last Refreshed: 20/09/2015 21:10:23
Number of Results: 197625
====Executing command 'npm install serialport2 --save '====

npm WARN package.json NodejsConsoleApp2@0.0.0 No repository field.
npm WARN package.json NodejsConsoleApp2@0.0.0 No license field.
npm WARN deprecated serialport2@0.0.5: Development has moved to serialport
> serialport2@0.0.5 install C:\Users\Adrien\Documents\Visual Studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\serialport2
> node-gyp rebuild
C:\Users\Adrien\Documents\Visual Studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\serialport2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:114:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:69:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Adrien\Documents\Visual Studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\node_modules\serialport2
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "serialport2" "--save"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! serialport2@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport2@0.0.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the serialport2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport2
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Adrien\Documents\Visual Studio 2015\Projects\NodejsConsoleApp2\NodejsConsoleApp2\npm-debug.log

====npm command completed with exit code 1====

**Comment by joeferner** [comment]
This package is no longer maintained. Please switch to serial port.
